version: '3'
services:
  db:
    image: ankane/pgvector
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: vector
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - '5433:5432'